(function(){
  'use strict';

  var counter=0,LOOP_MS=4300;
  var CONFIG={
    bold:{keys:['Ctrl','B'],label:'Fett formatieren',family:'doc'},
    newDoc:{keys:['Ctrl','N'],label:'Neues Dokument',family:'doc'},
    newTab:{keys:['Ctrl','T'],label:'Neuer Browser-Tab',family:'browser'},
    closeTab:{keys:['Ctrl','W'],label:'Browser-Tab schliessen',family:'browser'},
    reopenTab:{keys:['Ctrl','Shift','T'],label:'Tab wieder öffnen',family:'browser'},
    refresh:{keys:['F5'],label:'Webseite aktualisieren',family:'browser'},
    addressBar:{keys:['Ctrl','L'],label:'Adressleiste markieren',family:'browser'},
    nextTab:{keys:['Ctrl','Tab'],label:'Nächster Browser-Tab',family:'browser'},
    prevTab:{keys:['Ctrl','Shift','Tab'],label:'Vorheriger Browser-Tab',family:'browser'},
    lock:{keys:['Win','L'],label:'Computer sperren',family:'windows'},
    desktop:{keys:['Win','D'],label:'Desktop anzeigen',family:'windows'},
    explorer:{keys:['Win','E'],label:'Datei-Explorer öffnen',family:'windows'},
    snip:{keys:['Win','Shift','S'],label:'Bildschirmausschnitt',family:'windows'},
    appSwitch:{keys:['Alt','Tab'],label:'Programme wechseln',family:'windows'},
    taskManager:{keys:['Ctrl','Shift','Esc'],label:'Task-Manager öffnen',family:'windows'},
    clipboard:{keys:['Win','V'],label:'Zwischenablageverlauf',family:'windows'},
    closeWindow:{keys:['Alt','F4'],label:'Fenster schliessen',family:'windows'},
    snapLeft:{keys:['Win','←'],label:'Fenster links andocken',family:'windows'},
    snapRight:{keys:['Win','→'],label:'Fenster rechts andocken',family:'windows'}
  };

  function esc(v){return String(v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');}

  function createWindowResizeScene(container,type,options){
    options=options||{};
    var active=options.autoplay!==false,autoLoop=options.loop!==false,reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,timers=[],running=false,controller=null,uid='tk2a4resize'+(++counter),isMax=type==='maximize';

    container.innerHTML=''
      +'<svg data-window-resize-scene="'+type+'" viewBox="0 0 560 320" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Animation: '+(isMax?'Fenster maximieren':'Fenster verkleinern oder minimieren')+'">'
      +'<defs><filter id="'+uid+'Shadow" x="-30%" y="-30%" width="170%" height="180%"><feDropShadow dx="0" dy="8" stdDeviation="9" flood-color="#020617" flood-opacity=".38"/></filter></defs>'
      +'<rect width="560" height="320" rx="24" fill="#07101f"/>'
      +'<g class="desktop" filter="url(#'+uid+'Shadow)"><rect x="28" y="25" width="365" height="255" rx="17" fill="#0b5ea8"/><rect x="28" y="245" width="365" height="35" fill="#111827" opacity=".94"/><circle cx="205" cy="262" r="10" fill="#2563eb"/></g>'
      +'<g class="window" filter="url(#'+uid+'Shadow)"><rect x="112" y="58" width="225" height="158" rx="12" fill="#f8fafc"/><rect x="112" y="58" width="225" height="28" rx="12" fill="#dbe4ee"/><rect x="112" y="72" width="225" height="14" fill="#dbe4ee"/><text x="130" y="77" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Dokument</text><rect x="138" y="112" width="130" height="10" rx="5" fill="#334155"/><rect x="138" y="140" width="170" height="7" rx="3.5" fill="#94a3b8"/><rect x="138" y="158" width="150" height="7" rx="3.5" fill="#94a3b8"/></g>'
      +'<g class="direction" opacity="0"><rect x="447" y="95" width="76" height="76" rx="20" fill="#0f2746" opacity=".92" stroke="#1d4ed8" stroke-width="1.5"/><path d="'+(isMax?'M485 154V111M469 127l16-16 16 16':'M485 111v43M469 138l16 16 16-16')+'" fill="none" stroke="#93c5fd" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"/></g>'
      +'<g class="resize-guide" opacity="0">'+(isMax?'<rect x="43" y="38" width="340" height="198" rx="13" fill="#38bdf8" opacity=".10" stroke="#7dd3fc" stroke-width="2" stroke-dasharray="7 5"/>':'<path d="M225 188Q225 224 205 254" fill="none" stroke="#7dd3fc" stroke-width="2.5" stroke-dasharray="6 5"/><circle class="task-target" cx="205" cy="262" r="17" fill="#38bdf8" opacity=".18" stroke="#7dd3fc" stroke-width="2"/>')+'</g>'
      +'<g class="key-row" transform="translate(404 225)">'+window.tk2SceneKeycaps.markup(['Win',isMax?'↑':'↓'],'utility')+'</g>'
      +'<g class="toast" transform="translate(370 30)" opacity="0"><rect width="170" height="32" rx="16" fill="#052e2b" stroke="#10b981"/><text x="85" y="21" text-anchor="middle" font-family="Arial" font-size="10" font-weight="800" fill="#a7f3d0">'+(isMax?'Fenster maximiert':'Fenster minimiert')+'</text></g>'
      +'</svg>';

    var svg=container.querySelector('svg'),win=svg.querySelector('.window'),direction=svg.querySelector('.direction'),guide=svg.querySelector('.resize-guide'),toast=svg.querySelector('.toast'),keys=Array.from(svg.querySelectorAll('.tk2-u-key'));
    function later(ms,fn){timers.push(window.setTimeout(fn,ms));}
    function clearTimers(){timers.forEach(window.clearTimeout);timers=[];}
    function opacity(el,val){if(el)el.setAttribute('opacity',String(val));}
    function transform(el,val){if(el)el.setAttribute('transform',val);}
    function transition(el,val){if(el)el.style.transition=reduceMotion?'none':val;}
    function pressKeys(){window.tk2SceneKeycaps.pressSequence(keys,later,transition,'utility');}
    function reset(){clearTimers();running=false;transition(win,'none');if(guide)guide.style.transition='none';opacity(win,1);opacity(direction,0);opacity(guide,0);opacity(toast,0);transform(win,isMax?'translate(0 0) scale(1)':'translate(-38 -20) scale(1.24 1.16)');window.tk2SceneKeycaps.resetMany(keys);}
    function applyEnd(){transition(win,'none');if(isMax)transform(win,'translate(-126 -35) scale(1.51 1.25)');else{transform(win,'translate(126 186) scale(.20 .12)');opacity(win,.18);}opacity(direction,1);opacity(guide,0);opacity(toast,1);}
    function showEndState(){reset();applyEnd();}
    function run(){if(reduceMotion){showEndState();return;}reset();running=true;later(350,function(){opacity(direction,1);pressKeys();});later(760,function(){if(guide){transition(guide,'opacity 320ms ease');opacity(guide,1);}});later(1030,function(){transition(win,'transform 680ms cubic-bezier(.2,.8,.2,1),opacity 540ms ease');if(isMax)transform(win,'translate(-126 -35) scale(1.51 1.25)');else{transform(win,'translate(126 186) scale(.20 .12)');opacity(win,.18);}});later(1770,function(){if(guide){transition(guide,'opacity 300ms ease');opacity(guide,0);}opacity(toast,1);});later(5600,function(){running=false;if(active&&autoLoop)run();});}
    function play(){active=true;run();}
    function setActive(v){active=Boolean(v);if(!active){clearTimers();running=false;return;}if(!running)run();}
    controller={play:play,reset:reset,setActive:setActive};reset();if(active)setActive(true);return controller;
  }

  function createA4Scene(container,options){
    options=options||{};
    if(options.mode==='maximize'||options.mode==='minimize')return createWindowResizeScene(container,options.mode,options);
    var mode=options.mode||'newTab',cfg=CONFIG[mode]||CONFIG.newTab,active=options.autoplay!==false,autoLoop=options.loop!==false,reduceMotion=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches,uid='tk2a4'+(++counter),timers=[],running=false,controller=null,isA4Mode=['newDoc','newTab','closeTab','reopenTab','refresh','addressBar','nextTab','prevTab'].indexOf(mode)>=0,sceneLoopMs=cfg.family==='windows'?5600:(isA4Mode?4600:LOOP_MS);
    var keyProfile=cfg.family==='doc'?'doc':'utility';

    function browserMarkup(){return '<g class="browser" filter="url(#'+uid+'Shadow)"><rect x="28" y="25" width="365" height="255" rx="17" fill="#f8fafc"/><rect x="28" y="25" width="365" height="54" rx="17" fill="#dbe4ee"/><rect x="28" y="58" width="365" height="21" fill="#dbe4ee"/>'+
      '<g class="tabs"><g class="tab-one"><rect class="tab-one-bg" x="47" y="35" width="112" height="28" rx="9" fill="#fff"/><text x="103" y="53" text-anchor="middle" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Schulportal</text></g><g class="tab-two" opacity="0"><rect class="tab-two-bg" x="164" y="35" width="112" height="28" rx="9" fill="#dbe4ee"/><text x="220" y="53" text-anchor="middle" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Recherche</text></g><g class="tab-three" opacity="0"><rect x="281" y="35" width="92" height="28" rx="9" fill="#dbe4ee"/><text x="327" y="53" text-anchor="middle" font-family="Arial" font-size="8.5" font-weight="700" fill="#475569">Aufgaben</text></g><g class="tab-new" opacity="0"><rect x="164" y="35" width="112" height="28" rx="9" fill="#fff"/><text x="220" y="53" text-anchor="middle" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Neuer Tab</text></g><g class="tab-plus" opacity="0"><circle cx="337" cy="49" r="12" fill="#eef2f7" stroke="#cbd5e1"/><path d="M337 43v12M331 49h12" stroke="#64748b" stroke-width="2" stroke-linecap="round"/></g><rect class="active-tab-indicator" x="45" y="33" width="116" height="32" rx="11" fill="none" stroke="#60a5fa" stroke-width="2" opacity="0"/></g>'+
      '<rect class="address-box" x="48" y="91" width="318" height="28" rx="10" fill="#e2e8f0" stroke="#cbd5e1" stroke-width="1"/><rect class="address-highlight" x="56" y="97" width="0" height="16" rx="5" fill="#bfdbfe" opacity="0"/><text class="address-text" x="62" y="109" font-family="Arial" font-size="9" fill="#64748b">https://schule.example</text>'+
      '<g class="page-content"><rect class="page-title" x="54" y="142" width="132" height="13" rx="6" fill="#0f172a" opacity=".85"/><rect class="page-line page-line-1" x="54" y="172" width="275" height="8" rx="4" fill="#94a3b8"/><rect class="page-line page-line-2" x="54" y="191" width="238" height="8" rx="4" fill="#94a3b8"/><rect class="page-line page-line-3" x="54" y="210" width="264" height="8" rx="4" fill="#94a3b8"/><rect class="page-action" x="54" y="238" width="82" height="22" rx="8" fill="#3b82f6" opacity=".85"/></g><g class="page-content-alt" opacity="0" transform="translate(16 0)"><rect x="54" y="142" width="104" height="13" rx="6" fill="#0f172a" opacity=".82"/><rect x="54" y="172" width="226" height="8" rx="4" fill="#64748b"/><rect x="54" y="191" width="286" height="8" rx="4" fill="#94a3b8"/><rect x="54" y="210" width="204" height="8" rx="4" fill="#94a3b8"/><rect x="54" y="238" width="106" height="22" rx="8" fill="#14b8a6" opacity=".85"/></g>'+
      '<g class="refresh-ring" opacity="0" transform="translate(210 185)"><circle r="30" fill="#fff" stroke="#cbd5e1"/><g class="refresh-icon"><path d="M14 -16 A21 21 0 1 0 20 7" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round"/><path d="M20 7 L20 -3 M20 7 L10 5" fill="none" stroke="#2563eb" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/></g></g></g>';}

    function docMarkup(){return '<g class="doc" filter="url(#'+uid+'Shadow)"><rect x="28" y="25" width="365" height="255" rx="17" fill="#fff"/><rect x="28" y="25" width="365" height="38" rx="17" fill="#dbe4ee"/><rect x="28" y="46" width="365" height="17" fill="#dbe4ee"/><text x="55" y="49" font-family="Arial" font-size="10" font-weight="700" fill="#475569">Projektbericht.docx</text><rect x="57" y="88" width="148" height="13" rx="6" fill="#0f172a" opacity=".88"/><rect class="bold-selection" x="130" y="115" width="62" height="23" rx="3" fill="#bfdbfe" opacity="0"/><text x="57" y="133" font-family="Arial" font-size="15" fill="#334155">Das ist ein <tspan class="bold-word" font-weight="400">wichtiger</tspan> Satz.</text><rect x="57" y="158" width="260" height="8" rx="4" fill="#94a3b8"/><rect x="57" y="178" width="235" height="8" rx="4" fill="#94a3b8"/><rect x="57" y="198" width="270" height="8" rx="4" fill="#94a3b8"/><rect class="doc-dim" x="28" y="63" width="365" height="217" rx="0" fill="#0f172a" opacity="0"/><g class="new-doc-sheet" opacity="0"><rect x="48" y="76" width="322" height="183" rx="9" fill="#fff" stroke="#cbd5e1"/><text x="72" y="105" font-family="Arial" font-size="12" font-weight="700" fill="#334155">Neues Dokument</text><line class="new-doc-caret" x1="72" y1="130" x2="72" y2="151" stroke="#2563eb" stroke-width="2.5" opacity="0"/></g></g>';}

    function windowsMarkup(){return '<g class="desktop-base" filter="url(#'+uid+'Shadow)"><rect x="28" y="25" width="365" height="255" rx="17" fill="#0b5ea8"/><rect x="28" y="245" width="365" height="35" fill="#111827" opacity=".94"/><circle cx="205" cy="262" r="10" fill="#2563eb"/><rect class="active-app-dot" x="197" y="276" width="16" height="2.5" rx="1.25" fill="#93c5fd" opacity="0"/><g class="taskbar-explorer"><rect x="235" y="252" width="25" height="20" rx="5" fill="#1e293b" stroke="#64748b"/><path d="M240 259h7l3-3h5v11h-15z" fill="#fbbf24"/></g><rect class="explorer-active-dot" x="240" y="276" width="15" height="2.5" rx="1.25" fill="#60a5fa" opacity="0"/><g class="desktop-icons"><rect x="58" y="62" width="34" height="28" rx="5" fill="#f8fafc" opacity=".9"/><text x="75" y="104" text-anchor="middle" font-family="Arial" font-size="8" fill="#fff">Dateien</text><rect x="58" y="126" width="34" height="28" rx="5" fill="#f8fafc" opacity=".9"/><text x="75" y="168" text-anchor="middle" font-family="Arial" font-size="8" fill="#fff">Browser</text></g>'+
      '<g class="app-windows"><g class="desktop-extra-window" opacity="0" transform="translate(-30 24) scale(.88)"><rect x="118" y="55" width="220" height="154" rx="12" fill="#e0f2fe"/><rect x="118" y="55" width="220" height="27" rx="12" fill="#bae6fd"/><rect x="118" y="69" width="220" height="13" fill="#bae6fd"/><text x="136" y="73" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Browser</text><rect x="140" y="103" width="158" height="10" rx="5" fill="#0ea5e9" opacity=".65"/><rect x="140" y="130" width="170" height="7" rx="3.5" fill="#94a3b8"/></g><g class="app-one"><rect x="118" y="55" width="220" height="154" rx="12" fill="#f8fafc"/><rect x="118" y="55" width="220" height="27" rx="12" fill="#dbe4ee"/><rect x="118" y="69" width="220" height="13" fill="#dbe4ee"/><text x="136" y="73" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Dokument</text><g class="close-affordance" opacity="0"><circle cx="323" cy="68" r="8" fill="#ef4444"/><path d="M319 64l8 8M327 64l-8 8" stroke="#fff" stroke-width="1.8" stroke-linecap="round"/></g><g class="hung-badge" opacity="0"><rect x="224" y="91" width="101" height="20" rx="10" fill="#fee2e2" stroke="#ef4444"/><text x="274.5" y="104" text-anchor="middle" font-family="Arial" font-size="7.8" font-weight="800" fill="#991b1b">Keine Rückmeldung</text></g><rect x="140" y="103" width="130" height="10" rx="5" fill="#334155"/><rect x="140" y="130" width="170" height="7" rx="3.5" fill="#94a3b8"/><rect x="140" y="148" width="150" height="7" rx="3.5" fill="#94a3b8"/></g></g>'+
      '<g class="explorer-window" opacity="0"><rect x="98" y="48" width="250" height="174" rx="13" fill="#f8fafc"/><rect x="98" y="48" width="250" height="31" rx="13" fill="#dbe4ee"/><text x="118" y="68" font-family="Arial" font-size="9" font-weight="700" fill="#475569">Datei-Explorer</text><rect x="112" y="94" width="60" height="110" rx="8" fill="#eef2f7"/><rect x="188" y="97" width="56" height="44" rx="8" fill="#bfdbfe"/><rect x="258" y="97" width="56" height="44" rx="8" fill="#fde68a"/></g>'+
      '<g class="scene-lock" opacity="0"><rect x="28" y="25" width="365" height="255" rx="17" fill="#082f49"/><g class="lock-details" opacity="0"><text x="210" y="91" text-anchor="middle" font-family="Arial" font-size="34" font-weight="300" fill="#fff">10:42</text><text x="210" y="112" text-anchor="middle" font-family="Arial" font-size="9" fill="#bae6fd">Donnerstag · 27. August</text><circle cx="210" cy="154" r="22" fill="#cbd5e1" opacity=".9"/><circle cx="210" cy="147" r="8" fill="#64748b"/><path d="M194 171Q210 157 226 171" fill="#64748b"/><text x="210" y="198" text-anchor="middle" font-family="Arial" font-size="12" font-weight="800" fill="#fff">Computer gesperrt</text></g></g>'+
      '<g class="snip-overlay" opacity="0"><rect x="28" y="25" width="365" height="220" rx="17" fill="#020617" opacity=".58"/><g class="snip-toolbar" opacity="0" transform="translate(0 -10)"><rect x="129" y="39" width="166" height="32" rx="16" fill="#f8fafc" stroke="#cbd5e1"/><rect x="144" y="48" width="22" height="14" rx="3" fill="none" stroke="#2563eb" stroke-width="2"/><path d="M184 48h18v14h-18zM220 48h20v14M258 48l18 14M276 48l-18 14" fill="none" stroke="#64748b" stroke-width="1.7" stroke-linecap="round"/></g><g class="snip-cursor" opacity="0" transform="translate(126 92)"><path d="M-7 0h14M0-7v14" stroke="#fff" stroke-width="2" stroke-linecap="round"/><circle r="3" fill="#38bdf8"/></g><rect class="snip-box" x="116" y="82" width="0" height="0" rx="5" fill="none" stroke="#fff" stroke-width="2" stroke-dasharray="5 4"/><g class="snip-confirm" opacity="0" transform="translate(274 190) scale(.8)"><circle r="17" fill="#052e2b" stroke="#10b981" stroke-width="2"/><path d="M-7 0l5 5 10-11" fill="none" stroke="#a7f3d0" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/></g></g>'+
      '<g class="switcher" opacity="0"><rect x="73" y="91" width="286" height="116" rx="18" fill="#111827" opacity=".97"/><rect class="switch-focus" x="96" y="111" width="72" height="60" rx="10" fill="none" stroke="#60a5fa" stroke-width="3"/><g class="switch-a"><rect x="99" y="114" width="66" height="54" rx="8" fill="#fff" stroke="#334155"/><text x="132" y="146" text-anchor="middle" font-family="Arial" font-size="9" fill="#334155">Word</text></g><g class="switch-b"><rect x="181" y="114" width="66" height="54" rx="8" fill="#fff" stroke="#334155"/><text x="214" y="146" text-anchor="middle" font-family="Arial" font-size="9" fill="#334155">Browser</text></g><g class="switch-c"><rect x="263" y="114" width="66" height="54" rx="8" fill="#fff" stroke="#334155"/><text x="296" y="146" text-anchor="middle" font-family="Arial" font-size="9" fill="#334155">Explorer</text></g><text class="switch-caption" x="216" y="190" text-anchor="middle" font-family="Arial" font-size="9" font-weight="700" fill="#93c5fd">Word</text></g>'+
      '<g class="task-manager" opacity="0"><rect x="79" y="44" width="282" height="184" rx="14" fill="#f8fafc"/><rect x="79" y="44" width="282" height="32" rx="14" fill="#dbe4ee"/><text x="101" y="65" font-family="Arial" font-size="10" font-weight="700" fill="#475569">Task-Manager</text><text x="103" y="98" font-family="Arial" font-size="9" font-weight="700" fill="#64748b">Prozesse</text><text x="103" y="126" font-family="Arial" font-size="9" fill="#334155">Browser</text><rect x="192" y="118" width="112" height="10" rx="5" fill="#cbd5e1"/><g class="tm-problem-row" opacity="0"><rect x="94" y="135" width="246" height="29" rx="7" fill="#fee2e2" stroke="#fecaca"/><text x="103" y="153" font-family="Arial" font-size="9" font-weight="700" fill="#991b1b">Word · Keine Rückmeldung</text><rect x="261" y="144" width="66" height="10" rx="5" fill="#f87171" opacity=".72"/></g></g>'+
      '<g class="clipboard-panel" opacity="0"><rect x="118" y="44" width="220" height="184" rx="15" fill="#f8fafc"/><text x="139" y="70" font-family="Arial" font-size="11" font-weight="800" fill="#334155">Zwischenablage</text><g class="clip-item clip-item-1" opacity="0"><rect x="137" y="88" width="182" height="34" rx="8" fill="#e2e8f0"/><text x="149" y="109" font-family="Arial" font-size="9" fill="#475569">Projektgruppe B25</text></g><g class="clip-item clip-item-2" opacity="0"><rect x="137" y="132" width="182" height="34" rx="8" fill="#e2e8f0"/><text x="149" y="153" font-family="Arial" font-size="9" fill="#475569">https://schule.example</text></g><g class="clip-item clip-item-3" opacity="0"><rect x="137" y="176" width="182" height="34" rx="8" fill="#e2e8f0"/><text x="149" y="197" font-family="Arial" font-size="9" fill="#475569">Montag 08:10</text></g></g>'+
      '<g class="snap-zone snap-zone-left" opacity="0"><rect x="35" y="36" width="177" height="205" rx="12" fill="#38bdf8" opacity=".18" stroke="#7dd3fc" stroke-width="2" stroke-dasharray="6 5"/><path d="M212 43v191" stroke="#7dd3fc" stroke-width="1.5" opacity=".65"/></g><g class="snap-zone snap-zone-right" opacity="0"><rect x="209" y="36" width="177" height="205" rx="12" fill="#38bdf8" opacity=".18" stroke="#7dd3fc" stroke-width="2" stroke-dasharray="6 5"/><path d="M209 43v191" stroke="#7dd3fc" stroke-width="1.5" opacity=".65"/></g><g class="snap-left-window" opacity="0"><rect x="40" y="43" width="166" height="190" rx="10" fill="#f8fafc"/><rect x="40" y="43" width="166" height="27" rx="10" fill="#dbe4ee"/><text x="56" y="61" font-family="Arial" font-size="8" font-weight="700" fill="#475569">Dokument</text><rect x="58" y="92" width="112" height="8" rx="4" fill="#64748b"/><rect x="58" y="118" width="128" height="6" rx="3" fill="#cbd5e1"/></g>'+
      '<g class="snap-right-window" opacity="0"><rect x="215" y="43" width="166" height="190" rx="10" fill="#f8fafc"/><rect x="215" y="43" width="166" height="27" rx="10" fill="#dbe4ee"/><text x="231" y="61" font-family="Arial" font-size="8" font-weight="700" fill="#475569">Dokument</text><rect x="233" y="92" width="112" height="8" rx="4" fill="#64748b"/><rect x="233" y="118" width="128" height="6" rx="3" fill="#cbd5e1"/></g></g>';}

    var main=cfg.family==='browser'?browserMarkup():(cfg.family==='doc'?docMarkup():windowsMarkup()),keyRowWidth=window.tk2SceneKeycaps.rowWidth(cfg.keys,keyProfile),keyX=552-keyRowWidth,sceneDecoration=cfg.family==='windows'?'':'<circle cx="500" cy="42" r="100" fill="#06b6d4" opacity=".045"/>';
    container.innerHTML='<svg class="tk2-a4-scene" viewBox="0 0 560 320" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Animation: '+esc(cfg.label)+'"><defs><filter id="'+uid+'Shadow" x="-30%" y="-30%" width="170%" height="180%"><feDropShadow dx="0" dy="8" stdDeviation="9" flood-color="#020617" flood-opacity=".38"/></filter></defs><rect width="560" height="320" rx="24" fill="#07101f"/>'+sceneDecoration+main+'<g class="keys" transform="translate('+keyX+' 244)">'+window.tk2SceneKeycaps.markup(cfg.keys,keyProfile)+'</g><g class="toast" transform="translate(392 20)" opacity="0"><rect width="145" height="30" rx="15" fill="#052e2b" stroke="#10b981"/><text class="toast-text" x="72.5" y="19" text-anchor="middle" font-family="Arial" font-size="10" font-weight="800" fill="#a7f3d0">Fertig</text></g></svg>';

    var svg=container.querySelector('svg'),$=function(sel){return svg.querySelector(sel);},$$=function(sel){return Array.from(svg.querySelectorAll(sel));};
    function later(ms,fn){timers.push(window.setTimeout(fn,ms));}function clearTimers(){timers.forEach(window.clearTimeout);timers=[];}function trans(el,val){if(el)el.style.transition=reduceMotion?'none':val;}function opacity(el,val){if(el)el.setAttribute('opacity',String(val));}function toast(text){if($('.toast-text'))$('.toast-text').textContent=text;opacity($('.toast'),1);}function fill(el,val){if(el)el.setAttribute('fill',val);}function switchPage(toAlt,direction){var from=toAlt?$('.page-content'):$('.page-content-alt'),to=toAlt?$('.page-content-alt'):$('.page-content'),dx=direction>=0?14:-14;if(!from||!to)return;trans(from,'transform 500ms cubic-bezier(.2,.8,.2,1),opacity 360ms ease');trans(to,'transform 540ms cubic-bezier(.2,.8,.2,1),opacity 400ms ease');from.setAttribute('transform','translate('+(-dx)+' 0)');opacity(from,0);to.setAttribute('transform','translate('+dx+' 0)');opacity(to,1);later(30,function(){to.setAttribute('transform','translate(0 0)');});}
    function pressKeys(){window.tk2SceneKeycaps.pressSequence($$('.tk2-key, .tk2-u-key'),later,trans,keyProfile);}
    function reset(){
      clearTimers();running=false;
      window.tk2SceneKeycaps.resetMany($$('.tk2-key, .tk2-u-key'));
      opacity($('.toast'),0);
      if($('.bold-word'))$('.bold-word').setAttribute('font-weight','400');
      opacity($('.bold-selection'),0);opacity($('.new-doc-sheet'),0);opacity($('.new-doc-caret'),0);opacity($('.doc-dim'),0);

      var tabTwoVisible=['closeTab','nextTab','prevTab'].indexOf(mode)>=0;
      var tabThreeVisible=['closeTab','reopenTab'].indexOf(mode)>=0;
      opacity($('.tab-two'),tabTwoVisible?1:0);opacity($('.tab-three'),tabThreeVisible?1:0);opacity($('.tab-new'),0);opacity($('.tab-plus'),mode==='newTab'?1:0);opacity($('.active-tab-indicator'),['nextTab','prevTab'].indexOf(mode)>=0?1:0);
      if($('.tab-three'))$('.tab-three').setAttribute('transform',mode==='reopenTab'?'translate(-117 0)':'translate(0 0)');
      if($('.tab-two'))$('.tab-two').setAttribute('transform',mode==='reopenTab'?'translate(22 -8) scale(.92)':'translate(0 0) scale(1)');
      if($('.tab-new'))$('.tab-new').setAttribute('transform','translate(116 0) scale(.18 1)');
      if($('.tab-one'))$('.tab-one').setAttribute('transform','translate(0 0) scale(1)');
      if($('.active-tab-indicator'))$('.active-tab-indicator').setAttribute('transform',mode==='prevTab'?'translate(117 0)':'translate(0 0)');
      if($('.tabs'))$('.tabs').setAttribute('transform','translate(0 0)');

      opacity($('.refresh-ring'),0);if($('.refresh-ring'))$('.refresh-ring').setAttribute('transform','translate(210 185) rotate(0)');
      opacity($('.address-highlight'),0);if($('.address-highlight'))$('.address-highlight').setAttribute('width','0');
      if($('.address-box')){$('.address-box').setAttribute('stroke','#cbd5e1');$('.address-box').setAttribute('stroke-width','1');}
      if($('.address-text'))$('.address-text').setAttribute('fill','#64748b');

      var altFirst=mode==='reopenTab'||mode==='prevTab';
      if($('.page-content')){opacity($('.page-content'),altFirst?0:1);$('.page-content').setAttribute('transform',altFirst?'translate(-14 0)':'translate(0 0)');}
      if($('.page-content-alt')){opacity($('.page-content-alt'),altFirst?1:0);$('.page-content-alt').setAttribute('transform',altFirst?'translate(0 0)':'translate(14 0)');}
      $$('.page-title,.page-line,.page-action').forEach(function(el){opacity(el,1);el.setAttribute('transform','translate(0 0)');});

      fill($('.tab-one-bg'),mode==='prevTab'?'#dbe4ee':'#fff');fill($('.tab-two-bg'),mode==='prevTab'?'#fff':'#dbe4ee');
      opacity($('.scene-lock'),0);opacity($('.lock-details'),0);opacity($('.app-windows'),1);opacity($('.app-one'),1);opacity($('.desktop-extra-window'),mode==='desktop'?.74:0);opacity($('.explorer-window'),0);opacity($('.explorer-active-dot'),0);opacity($('.active-app-dot'),mode==='closeWindow'?1:0);opacity($('.close-affordance'),mode==='closeWindow'?1:0);opacity($('.hung-badge'),0);opacity($('.tm-problem-row'),0);opacity($('.snip-overlay'),0);opacity($('.snip-toolbar'),0);opacity($('.snip-cursor'),0);opacity($('.snip-confirm'),0);opacity($('.snap-zone-left'),0);opacity($('.snap-zone-right'),0);if($('.snip-toolbar'))$('.snip-toolbar').setAttribute('transform','translate(0 -10)');if($('.snip-cursor'))$('.snip-cursor').setAttribute('transform','translate(126 92)');if($('.snip-confirm'))$('.snip-confirm').setAttribute('transform','translate(274 190) scale(.8)');if($('.switch-focus'))$('.switch-focus').setAttribute('transform','translate(0 0)');if($('.switch-caption'))$('.switch-caption').textContent='Word';if($('.app-one'))$('.app-one').setAttribute('transform','translate(0 0) scale(1)');if($('.desktop-icons')){opacity($('.desktop-icons'),1);$('.desktop-icons').setAttribute('transform','translate(0 0) scale(1)');}$$('.clip-item').forEach(function(el){opacity(el,0);el.setAttribute('transform','translate(0 8)');});
      if($('.snip-box')){$('.snip-box').setAttribute('width','0');$('.snip-box').setAttribute('height','0');}
      opacity($('.switcher'),0);opacity($('.task-manager'),0);opacity($('.clipboard-panel'),0);opacity($('.snap-left-window'),0);opacity($('.snap-right-window'),0);

      [$('.new-doc-sheet'),$('.new-doc-caret'),$('.doc-dim'),$('.tab-one'),$('.tab-new'),$('.tab-two'),$('.tab-three'),$('.tab-plus'),$('.active-tab-indicator'),$('.tabs'),$('.refresh-ring'),$('.address-highlight'),$('.address-box'),$('.page-content'),$('.page-content-alt'),$('.switcher'),$('.switch-focus'),$('.snip-overlay'),$('.snip-toolbar'),$('.snip-cursor'),$('.snip-confirm'),$('.snap-zone-left'),$('.snap-zone-right'),$('.app-one'),$('.app-windows'),$('.scene-lock'),$('.lock-details'),$('.desktop-icons'),$('.taskbar-explorer'),$('.explorer-active-dot'),$('.active-app-dot'),$('.close-affordance'),$('.hung-badge'),$('.task-manager'),$('.tm-problem-row'),$('.clipboard-panel'),$('.snap-left-window'),$('.snap-right-window')].forEach(function(el){if(el)trans(el,'none');});$$('.clip-item').forEach(function(el){trans(el,'none');});
      [$('.app-windows'),$('.scene-lock'),$('.explorer-window'),$('.task-manager'),$('.clipboard-panel'),$('.snap-left-window'),$('.snap-right-window')].forEach(function(el){if(el)el.setAttribute('transform','translate(0 0) scale(1)');});
      if($('.switch-a rect')){$('.switch-a rect').style.transition='none';$('.switch-a rect').setAttribute('stroke','#60a5fa');}
      if($('.switch-b rect')){$('.switch-b rect').style.transition='none';$('.switch-b rect').setAttribute('stroke','#334155');}
    }
    function applyEnd(){
      if(mode==='bold'){opacity($('.bold-selection'),0);$('.bold-word').setAttribute('font-weight','800');toast('Text ist fett');}
      else if(mode==='newDoc'){opacity($('.new-doc-sheet'),1);toast('Neues Dokument');}
      else if(mode==='newTab'){opacity($('.tab-new'),1);toast('Neuer Tab');}
      else if(mode==='closeTab'){opacity($('.tab-two'),0);toast('Tab geschlossen');}
      else if(mode==='reopenTab'){opacity($('.tab-two'),1);toast('Tab wieder geöffnet');}
      else if(mode==='refresh'){toast('Seite aktualisiert');}
      else if(mode==='addressBar'){opacity($('.address-highlight'),1);if($('.address-text'))$('.address-text').setAttribute('fill','#1e3a8a');toast('Adresse markiert');}
      else if(mode==='nextTab'){fill($('.tab-one-bg'),'#dbe4ee');fill($('.tab-two-bg'),'#fff');toast('Nächster Tab');}
      else if(mode==='prevTab'){fill($('.tab-one-bg'),'#fff');fill($('.tab-two-bg'),'#dbe4ee');toast('Vorheriger Tab');}
      else if(mode==='lock'){opacity($('.scene-lock'),1);opacity($('.lock-details'),1);toast('Computer gesperrt');}
      else if(mode==='desktop'){opacity($('.app-windows'),0);toast('Desktop sichtbar');}
      else if(mode==='explorer'){opacity($('.explorer-window'),1);opacity($('.explorer-active-dot'),1);toast('Explorer geöffnet');}
      else if(mode==='snip'){opacity($('.snip-overlay'),1);opacity($('.snip-toolbar'),1);opacity($('.snip-confirm'),1);$('.snip-box').setAttribute('width','180');$('.snip-box').setAttribute('height','104');toast('Ausschnitt gewählt');}
      else if(mode==='appSwitch'){opacity($('.switcher'),0);opacity($('.app-one'),0);opacity($('.desktop-extra-window'),1);if($('.switch-caption'))$('.switch-caption').textContent='Browser';toast('Zum Browser gewechselt');}
      else if(mode==='taskManager'){opacity($('.task-manager'),1);opacity($('.hung-badge'),1);opacity($('.tm-problem-row'),1);toast('Task-Manager geöffnet');}
      else if(mode==='clipboard'){opacity($('.clipboard-panel'),1);$$('.clip-item').forEach(function(el){opacity(el,1);el.setAttribute('transform','translate(0 0)');});toast('Verlauf geöffnet');}
      else if(mode==='closeWindow'){opacity($('.app-windows'),0);opacity($('.active-app-dot'),0);opacity($('.close-affordance'),0);toast('Fenster geschlossen');}
      else if(mode==='snapLeft'){opacity($('.app-windows'),0);opacity($('.snap-left-window'),1);toast('Links angedockt');}
      else if(mode==='snapRight'){opacity($('.app-windows'),0);opacity($('.snap-right-window'),1);toast('Rechts angedockt');}
    }
    function showEndState(){reset();applyEnd();}
    function playMode(){
      var keyDelay=mode==='reopenTab'?800:420;
      var actionAt=Math.max(1080,keyDelay+Math.max(0,cfg.keys.length-1)*190+280);
      if(mode==='bold')later(140,function(){opacity($('.bold-selection'),1);});
      later(keyDelay,pressKeys);

      // 1) Ctrl+W / Ctrl+Shift+T: the neighbouring tab visibly occupies/frees the slot.
      if(mode==='closeTab'){later(actionAt,function(){var closing=$('.tab-two'),next=$('.tab-three');trans(closing,'transform 500ms cubic-bezier(.2,.8,.2,1),opacity 340ms ease');trans(next,'transform 560ms cubic-bezier(.2,.8,.2,1)');closing.setAttribute('transform','translate(-8 -9) scale(.84)');opacity(closing,0);next.setAttribute('transform','translate(-117 0)');switchPage(true,1);});later(actionAt+650,function(){toast('Tab geschlossen');});return;}
      if(mode==='reopenTab'){later(actionAt,function(){var restored=$('.tab-two'),next=$('.tab-three');trans(next,'transform 560ms cubic-bezier(.2,.8,.2,1)');trans(restored,'transform 520ms cubic-bezier(.2,.8,.2,1),opacity 360ms ease');next.setAttribute('transform','translate(0 0)');opacity(restored,1);later(35,function(){restored.setAttribute('transform','translate(0 0) scale(1)');});switchPage(false,-1);});later(actionAt+650,function(){toast('Tab wieder geöffnet');});return;}

      // 2) F5: page fades, loader rotates, content returns instead of a single frame swap.
      if(mode==='refresh'){later(930,function(){var page=$('.page-content'),ring=$('.refresh-ring');trans(page,'transform 420ms ease,opacity 340ms ease');page.setAttribute('transform','translate(0 4)');opacity(page,.16);trans(ring,'transform 760ms linear,opacity 220ms ease');opacity(ring,1);later(30,function(){ring.setAttribute('transform','translate(210 185) rotate(360)');});});later(1580,function(){var page=$('.page-content'),parts=$$('.page-title,.page-line,.page-action');trans(page,'transform 320ms ease,opacity 220ms ease');page.setAttribute('transform','translate(0 0)');opacity(page,1);parts.forEach(function(el){trans(el,'none');opacity(el,0);el.setAttribute('transform','translate(0 7)');});parts.forEach(function(el,index){later(index*110,function(){trans(el,'transform 360ms cubic-bezier(.2,.8,.2,1),opacity 300ms ease');opacity(el,1);el.setAttribute('transform','translate(0 0)');});});});later(2160,function(){opacity($('.refresh-ring'),0);toast('Seite aktualisiert');});return;}

      // 3) Ctrl+Tab / Ctrl+Shift+Tab: an outline physically moves to the destination tab.
      if(mode==='nextTab'||mode==='prevTab'){later(actionAt,function(){var one=$('.tab-one-bg'),two=$('.tab-two-bg'),indicator=$('.active-tab-indicator'),tabs=$('.tabs');trans(one,'fill 520ms ease');trans(two,'fill 520ms ease');trans(indicator,'transform 560ms cubic-bezier(.2,.8,.2,1)');trans(tabs,'transform 260ms ease');tabs.setAttribute('transform',mode==='nextTab'?'translate(-4 0)':'translate(4 0)');indicator.setAttribute('transform',mode==='nextTab'?'translate(117 0)':'translate(0 0)');if(mode==='nextTab'){fill(one,'#dbe4ee');fill(two,'#fff');switchPage(true,1);}else{fill(one,'#fff');fill(two,'#dbe4ee');switchPage(false,-1);}later(270,function(){tabs.setAttribute('transform','translate(0 0)');});});later(actionAt+650,function(){toast(mode==='nextTab'?'Nächster Tab':'Vorheriger Tab');});return;}

      // 4) Ctrl+N: new sheet comes forward and the caret confirms a live new document.
      if(mode==='newDoc'){later(actionAt-140,function(){var dim=$('.doc-dim');trans(dim,'opacity 360ms ease');opacity(dim,.52);});later(actionAt,function(){var sheet=$('.new-doc-sheet');sheet.setAttribute('transform','translate(0 18) scale(.95)');trans(sheet,'transform 580ms cubic-bezier(.2,.8,.2,1),opacity 400ms ease');opacity(sheet,1);later(35,function(){sheet.setAttribute('transform','translate(0 0) scale(1)');});});later(actionAt+610,function(){var caret=$('.new-doc-caret');trans(caret,'opacity 180ms ease');opacity(caret,1);});later(actionAt+930,function(){opacity($('.new-doc-caret'),0);});later(actionAt+1170,function(){opacity($('.new-doc-caret'),1);toast('Neues Dokument');});return;}

      // 5) Ctrl+T: the new tab grows out of the plus area and becomes active.
      if(mode==='newTab'){later(actionAt,function(){var tab=$('.tab-new'),plus=$('.tab-plus'),first=$('.tab-one');trans(first,'transform 360ms ease');first.setAttribute('transform','translate(-5 0) scale(.985)');trans(tab,'transform 560ms cubic-bezier(.2,.8,.2,1),opacity 360ms ease');trans(plus,'transform 300ms ease,opacity 260ms ease');plus.setAttribute('transform','scale(.72)');opacity(plus,0);opacity(tab,1);later(35,function(){tab.setAttribute('transform','translate(0 0) scale(1)');});later(430,function(){first.setAttribute('transform','translate(0 0) scale(1)');});});later(actionAt+620,function(){toast('Neuer Tab');});return;}

      // 6) Ctrl+L: focus ring + a real left-to-right selection sweep across the URL.
      if(mode==='addressBar'){later(actionAt,function(){var box=$('.address-box'),mark=$('.address-highlight');trans(box,'stroke 220ms ease,stroke-width 220ms ease');box.setAttribute('stroke','#60a5fa');box.setAttribute('stroke-width','4');later(240,function(){trans(box,'stroke 300ms ease,stroke-width 300ms ease');box.setAttribute('stroke','#3b82f6');box.setAttribute('stroke-width','2');});trans(mark,'width 560ms cubic-bezier(.2,.8,.2,1),opacity 220ms ease');opacity(mark,1);mark.setAttribute('width','286');if($('.address-text')){trans($('.address-text'),'fill 420ms ease');$('.address-text').setAttribute('fill','#1e3a8a');}});later(actionAt+650,function(){toast('Adresse markiert');});return;}

      if(mode==='snip'){later(900,function(){var overlay=$('.snip-overlay'),toolbar=$('.snip-toolbar');trans(overlay,'opacity 380ms ease');opacity(overlay,1);trans(toolbar,'transform 460ms cubic-bezier(.2,.8,.2,1),opacity 320ms ease');opacity(toolbar,1);later(30,function(){toolbar.setAttribute('transform','translate(0 0)');});});later(1260,function(){var cursor=$('.snip-cursor');trans(cursor,'transform 520ms cubic-bezier(.2,.8,.2,1),opacity 220ms ease');opacity(cursor,1);cursor.setAttribute('transform','translate(126 92)');later(30,function(){cursor.setAttribute('transform','translate(292 190)');});});later(1450,function(){var box=$('.snip-box');trans(box,'width 650ms cubic-bezier(.2,.8,.2,1),height 650ms cubic-bezier(.2,.8,.2,1)');box.setAttribute('width','180');box.setAttribute('height','104');});later(2180,function(){opacity($('.snip-cursor'),0);var ok=$('.snip-confirm');trans(ok,'transform 380ms cubic-bezier(.2,.8,.2,1),opacity 260ms ease');opacity(ok,1);ok.setAttribute('transform','translate(274 190) scale(1)');toast('Ausschnitt gewählt');});return;}
      if(mode==='appSwitch'){later(900,function(){var sw=$('.switcher');sw.setAttribute('transform','translate(0 14) scale(.95)');trans(sw,'transform 460ms cubic-bezier(.2,.8,.2,1),opacity 340ms ease');opacity(sw,1);later(30,function(){sw.setAttribute('transform','translate(0 0) scale(1)');});});later(1430,function(){var focus=$('.switch-focus');trans(focus,'transform 540ms cubic-bezier(.2,.8,.2,1)');focus.setAttribute('transform','translate(82 0)');if($('.switch-caption'))$('.switch-caption').textContent='Browser';});later(2070,function(){var sw=$('.switcher'),word=$('.app-one'),browser=$('.desktop-extra-window');trans(sw,'transform 360ms ease,opacity 300ms ease');sw.setAttribute('transform','translate(0 -8) scale(.98)');opacity(sw,0);trans(word,'transform 440ms ease,opacity 320ms ease');word.setAttribute('transform','translate(-16 7) scale(.96)');opacity(word,.18);browser.setAttribute('transform','translate(18 8) scale(.96)');trans(browser,'transform 560ms cubic-bezier(.2,.8,.2,1),opacity 400ms ease');opacity(browser,1);later(30,function(){browser.setAttribute('transform','translate(0 0) scale(1)');});});later(2700,function(){toast('Zum Browser gewechselt');});return;}
      if(mode==='desktop'){later(actionAt-150,function(){var icons=$('.desktop-icons');trans(icons,'transform 420ms ease,opacity 320ms ease');icons.setAttribute('transform','translate(0 7) scale(.985)');opacity(icons,.68);});later(actionAt,function(){var w=$('.app-windows');trans(w,'transform 680ms cubic-bezier(.2,.8,.2,1),opacity 540ms ease');w.setAttribute('transform','translate(0 124) scale(.64)');opacity(w,0);});later(actionAt+500,function(){var icons=$('.desktop-icons');trans(icons,'transform 520ms cubic-bezier(.2,.8,.2,1),opacity 420ms ease');icons.setAttribute('transform','translate(0 0) scale(1)');opacity(icons,1);});later(actionAt+760,function(){toast('Desktop sichtbar');});return;}
      if(mode==='lock'){later(actionAt-170,function(){var w=$('.app-windows');trans(w,'transform 360ms ease,opacity 320ms ease');w.setAttribute('transform','translate(0 5) scale(.985)');opacity(w,.28);});later(actionAt,function(){var lock=$('.scene-lock'),details=$('.lock-details');lock.setAttribute('transform','translate(0 10) scale(1.018)');trans(lock,'transform 620ms cubic-bezier(.2,.8,.2,1),opacity 480ms ease');opacity(lock,1);later(30,function(){lock.setAttribute('transform','translate(0 0) scale(1)');});later(260,function(){trans(details,'transform 460ms cubic-bezier(.2,.8,.2,1),opacity 360ms ease');details.setAttribute('transform','translate(0 8)');opacity(details,1);later(30,function(){details.setAttribute('transform','translate(0 0)');});});});later(actionAt+760,function(){toast('Computer gesperrt');});return;}
      if(mode==='explorer'){later(actionAt-120,function(){var icon=$('.taskbar-explorer'),dot=$('.explorer-active-dot');trans(icon,'transform 260ms ease');icon.setAttribute('transform','translate(-2 -2) scale(1.12)');opacity(dot,1);later(260,function(){icon.setAttribute('transform','translate(0 0) scale(1)');});});later(actionAt,function(){var panel=$('.explorer-window');panel.setAttribute('transform','translate(215 182) scale(.20)');trans(panel,'transform 680ms cubic-bezier(.16,.84,.22,1),opacity 440ms ease');opacity(panel,1);later(30,function(){panel.setAttribute('transform','translate(0 0) scale(1)');});});later(actionAt+740,function(){toast('Explorer geöffnet');});return;}
      if(mode==='taskManager'){later(actionAt-260,function(){var badge=$('.hung-badge');badge.setAttribute('transform','scale(.94)');trans(badge,'transform 320ms cubic-bezier(.2,.8,.2,1),opacity 260ms ease');opacity(badge,1);later(30,function(){badge.setAttribute('transform','scale(1)');});});later(actionAt,function(){var panel=$('.task-manager');panel.setAttribute('transform','translate(0 20) scale(.95)');trans(panel,'transform 600ms cubic-bezier(.2,.8,.2,1),opacity 420ms ease');opacity(panel,1);later(30,function(){panel.setAttribute('transform','translate(0 0) scale(1)');});});later(actionAt+520,function(){var row=$('.tm-problem-row');trans(row,'opacity 360ms ease');opacity(row,1);});later(actionAt+820,function(){toast('Task-Manager geöffnet');});return;}
      if(mode==='clipboard'){later(actionAt,function(){var panel=$('.clipboard-panel');panel.setAttribute('transform','translate(0 82) scale(.96)');trans(panel,'transform 620ms cubic-bezier(.2,.8,.2,1),opacity 420ms ease');opacity(panel,1);later(30,function(){panel.setAttribute('transform','translate(0 0) scale(1)');});});$$('.clip-item').forEach(function(item,index){later(actionAt+360+index*130,function(){trans(item,'transform 360ms cubic-bezier(.2,.8,.2,1),opacity 300ms ease');opacity(item,1);item.setAttribute('transform','translate(0 0)');});});later(actionAt+860,function(){toast('Verlauf geöffnet');});return;}
      if(mode==='closeWindow'){later(actionAt-180,function(){var close=$('.close-affordance');trans(close,'transform 260ms ease,opacity 220ms ease');close.setAttribute('transform','scale(1.22)');later(220,function(){close.setAttribute('transform','scale(1)');});});later(actionAt,function(){var w=$('.app-windows'),dot=$('.active-app-dot');trans(w,'transform 680ms cubic-bezier(.2,.8,.2,1),opacity 500ms ease');w.setAttribute('transform','translate(72 154) scale(.30)');opacity(w,0);later(380,function(){trans(dot,'opacity 260ms ease');opacity(dot,0);});});later(actionAt+760,function(){opacity($('.close-affordance'),0);toast('Fenster geschlossen');});return;}
      if(mode==='snapLeft'||mode==='snapRight'){later(actionAt-180,function(){var zone=mode==='snapLeft'?$('.snap-zone-left'):$('.snap-zone-right');trans(zone,'opacity 300ms ease');opacity(zone,1);});later(actionAt,function(){var w=$('.app-windows'),target=mode==='snapLeft'?$('.snap-left-window'):$('.snap-right-window'),zone=mode==='snapLeft'?$('.snap-zone-left'):$('.snap-zone-right');trans(w,'transform 620ms cubic-bezier(.2,.8,.2,1),opacity 440ms ease');w.setAttribute('transform',mode==='snapLeft'?'translate(-89 4) scale(.76)':'translate(89 4) scale(.76)');opacity(w,.10);target.setAttribute('transform',mode==='snapLeft'?'translate(-28 0) scale(.92)':'translate(28 0) scale(.92)');trans(target,'transform 620ms cubic-bezier(.2,.8,.2,1),opacity 420ms ease');opacity(target,1);later(30,function(){target.setAttribute('transform','translate(0 0) scale(1)');});later(520,function(){trans(zone,'opacity 320ms ease');opacity(zone,0);});});later(actionAt+700,function(){toast(mode==='snapLeft'?'Links angedockt':'Rechts angedockt');});return;}
      later(actionAt,applyEnd);
    }
    function run(){if(reduceMotion){showEndState();return;}reset();running=true;playMode();later(sceneLoopMs,function(){running=false;if(active&&autoLoop)run();});}
    function play(){active=true;run();}
    function setActive(v){active=Boolean(v);if(!active){clearTimers();running=false;return;}if(!running)run();}
    controller={play:play,reset:reset,setActive:setActive};
    reset();if(active)setActive(true);return controller;
  }

  window.createA4Scene=createA4Scene;
})();